import comtypes.client

CO_E_OBJNOTCONNECTED = -2147220995
UIAutomationCore = comtypes.client.GetModule("UIAutomationCore.dll")
IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-54103eef594e}",
                                             interface=UIAutomationCore.IUIAutomation)

_IUIAutomation = comtypes.CoCreateInstance(comtypes.gen.UIAutomationClient.CUIAutomation._reg_clsid_,
                                           interface=comtypes.gen.UIAutomationClient.IUIAutomation,
                                           clsctx=comtypes.CLSCTX_INPROC_SERVER)

UIAutomationClient = comtypes.gen.UIAutomationClient


_control_type = {
    UIAutomationClient.UIA_ButtonControlTypeId: 'UIA_ButtonControlTypeId',
    UIAutomationClient.UIA_CalendarControlTypeId: 'UIA_CalendarControlTypeId',
    UIAutomationClient.UIA_CheckBoxControlTypeId: 'UIA_CheckBoxControlTypeId',
    UIAutomationClient.UIA_ComboBoxControlTypeId: 'UIA_ComboBoxControlTypeId',
    UIAutomationClient.UIA_CustomControlTypeId: 'UIA_CustomControlTypeId',
    UIAutomationClient.UIA_DataGridControlTypeId: 'UIA_DataGridControlTypeId',
    UIAutomationClient.UIA_DataItemControlTypeId: 'UIA_DataItemControlTypeId',
    UIAutomationClient.UIA_DocumentControlTypeId: 'UIA_DocumentControlTypeId',
    UIAutomationClient.UIA_EditControlTypeId: 'UIA_EditControlTypeId',
    UIAutomationClient.UIA_GroupControlTypeId: 'UIA_GroupControlTypeId',
    UIAutomationClient.UIA_HeaderControlTypeId: 'UIA_HeaderControlTypeId',
    UIAutomationClient.UIA_HeaderItemControlTypeId: 'UIA_HeaderItemControlTypeId',
    UIAutomationClient.UIA_HyperlinkControlTypeId: 'UIA_HyperlinkControlTypeId',
    UIAutomationClient.UIA_ImageControlTypeId: 'UIA_ImageControlTypeId',
    UIAutomationClient.UIA_ListControlTypeId: 'UIA_ListControlTypeId',
    UIAutomationClient.UIA_ListItemControlTypeId: 'UIA_ListItemControlTypeId',
    UIAutomationClient.UIA_MenuBarControlTypeId: 'UIA_MenuBarControlTypeId',
    UIAutomationClient.UIA_MenuControlTypeId: 'UIA_MenuControlTypeId',
    UIAutomationClient.UIA_MenuItemControlTypeId: 'UIA_MenuItemControlTypeId',
    UIAutomationClient.UIA_PaneControlTypeId: 'UIA_PaneControlTypeId',
    UIAutomationClient.UIA_ProgressBarControlTypeId: 'UIA_ProgressBarControlTypeId',
    UIAutomationClient.UIA_RadioButtonControlTypeId: 'UIA_RadioButtonControlTypeId',
    UIAutomationClient.UIA_ScrollBarControlTypeId: 'UIA_ScrollBarControlTypeId',
    UIAutomationClient.UIA_SeparatorControlTypeId: 'UIA_SeparatorControlTypeId',
    UIAutomationClient.UIA_SliderControlTypeId: 'UIA_SliderControlTypeId',
    UIAutomationClient.UIA_SpinnerControlTypeId: 'UIA_SpinnerControlTypeId',
    UIAutomationClient.UIA_SplitButtonControlTypeId: 'UIA_SplitButtonControlTypeId',
    UIAutomationClient.UIA_StatusBarControlTypeId: 'UIA_StatusBarControlTypeId',
    UIAutomationClient.UIA_TabControlTypeId: 'UIA_TabControlTypeId',
    UIAutomationClient.UIA_TabItemControlTypeId: 'UIA_TabItemControlTypeId',
    UIAutomationClient.UIA_TableControlTypeId: 'UIA_TableControlTypeId',
    UIAutomationClient.UIA_TextControlTypeId: 'UIA_TextControlTypeId',
    UIAutomationClient.UIA_ThumbControlTypeId: 'UIA_ThumbControlTypeId',
    UIAutomationClient.UIA_TitleBarControlTypeId: 'UIA_TitleBarControlTypeId',
    UIAutomationClient.UIA_ToolBarControlTypeId: 'UIA_ToolBarControlTypeId',
    UIAutomationClient.UIA_ToolTipControlTypeId: 'UIA_ToolTipControlTypeId',
    UIAutomationClient.UIA_TreeControlTypeId: 'UIA_TreeControlTypeId',
    UIAutomationClient.UIA_TreeItemControlTypeId: 'UIA_TreeItemControlTypeId',
    UIAutomationClient.UIA_WindowControlTypeId: 'UIA_WindowControlTypeId'
}

_tree_scope = {
    'ancestors': UIAutomationClient.TreeScope_Ancestors,
    'children': UIAutomationClient.TreeScope_Children,
    'descendants': UIAutomationClient.TreeScope_Descendants,
    'element': UIAutomationClient.TreeScope_Element,
    'parent': UIAutomationClient.TreeScope_Parent,
    'subtree': UIAutomationClient.TreeScope_Subtree
}

# Define the state codes and their corresponding text
state_dict = {
    0x1: "unavailable",
    0x2: "selected",
    0x4: "focused",
    0x8: "pressed",
    0x10: "checked",
    0x20: "mixed",
    0x40: "readonly",
    0x80: "hottracked",
    0x100: "default",
    0x200: "expanded",
    0x400: "collapsed",
    0x800: "busy",
    0x1000: "floating",
    0x2000: "marqueed",
    0x4000: "animated",
    0x8000: "invisible",
    0x10000: "offscreen",
    0x20000: "resizable",
    0x40000: "movable",
    0x80000: "selfvoicing",
    0x100000: "focusable",
    0x200000: "selectable",
    0x400000: "linked",
    0x800000: "traversed",
    0x1000000: "multiselectable",
    0x2000000: "extselectable"
}

property_id = {
        "AcceleratorKeyProperty": 30006,
        "AccessKeyProperty": 30007,
        "AnnotationAnnotationTypeIdProperty": 30113,
        "AnnotationAnnotationTypeNameProperty": 30114,
        "AnnotationAuthorProperty": 30115,
        "AnnotationDateTimeProperty": 30116,
        "AnnotationObjectsProperty": 30156,
        "AnnotationTargetProperty": 30117,
        "AnnotationTypesProperty": 30155,
        "AriaPropertiesProperty": 30102,
        "AriaRoleProperty": 30101,
        "AutomationIdProperty": 30011,
        "BoundingRectangleProperty": 30001,
        "CenterPointProperty": 30165,
        "ClassNameProperty": 30012,
        "ClickablePointProperty": 30014,
        "ControlTypeProperty": 30003,
        "ControllerForProperty": 30104,
        "CultureProperty": 30015,
        "DescribedByProperty": 30105,
        "DockDockPositionProperty": 30069,
        "DragDropEffectProperty": 30139,
        "DragDropEffectsProperty": 30140,
        "DragGrabbedItemsProperty": 30144,
        "DragIsGrabbedProperty": 30138,
        "DropTargetDropTargetEffectProperty": 30142,
        "DropTargetDropTargetEffectsProperty": 30143,
        "ExpandCollapseExpandCollapseStateProperty": 30070,
        "FillColorProperty": 30160,
        "FillTypeProperty": 30162,
        "FlowsFromProperty": 30148,
        "FlowsToProperty": 30106,
        "FrameworkIdProperty": 30024,
        "FullDescriptionProperty": 30159,
        "GridColumnCountProperty": 30063,
        "GridItemColumnProperty": 30065,
        "GridItemColumnSpanProperty": 30067,
        "GridItemContainingGridProperty": 30068,
        "GridItemRowProperty": 30064,
        "GridItemRowSpanProperty": 30066,
        "GridRowCountProperty": 30062,
        "HasKeyboardFocusProperty": 30008,
        "HelpTextProperty": 30013,
        "IsAnnotationPatternAvailableProperty": 30118,
        "IsContentElementProperty": 30017,
        "IsControlElementProperty": 30016,
        "IsCustomNavigationPatternAvailableProperty": 30151,
        "IsDataValidForFormProperty": 30103,
        "IsDockPatternAvailableProperty": 30027,
        "IsDragPatternAvailableProperty": 30137,
        "IsDropTargetPatternAvailableProperty": 30141,
        "IsEnabledProperty": 30010,
        "IsExpandCollapsePatternAvailableProperty": 30028,
        "IsGridItemPatternAvailableProperty": 30029,
        "IsGridPatternAvailableProperty": 30030,
        "IsInvokePatternAvailableProperty": 30031,
        "IsItemContainerPatternAvailableProperty": 30108,
        "IsKeyboardFocusableProperty": 30009,
        "IsLegacyIAccessiblePatternAvailableProperty": 30090,
        "IsMultipleViewPatternAvailableProperty": 30032,
        "IsObjectModelPatternAvailableProperty": 30112,
        "IsOffscreenProperty": 30022,
        "IsPasswordProperty": 30019,
        "IsPeripheralProperty": 30150,
        "IsRangeValuePatternAvailableProperty": 30033,
        "IsRequiredForFormProperty": 30025,
        "IsScrollItemPatternAvailableProperty": 30035,
        "IsScrollPatternAvailableProperty": 30034,
        "IsSelectionItemPatternAvailableProperty": 30036,
        "IsSelectionPattern2AvailableProperty": 30168,
        "IsSelectionPatternAvailableProperty": 30037,
        "IsSpreadsheetItemPatternAvailableProperty": 30132,
        "IsSpreadsheetPatternAvailableProperty": 30128,
        "IsStylesPatternAvailableProperty": 30127,
        "IsSynchronizedInputPatternAvailableProperty": 30110,
        "IsTableItemPatternAvailableProperty": 30039,
        "IsTablePatternAvailableProperty": 30038,
        "IsTextChildPatternAvailableProperty": 30136,
        "IsTextEditPatternAvailableProperty": 30149,
        "IsTextPattern2AvailableProperty": 30119,
        "IsTextPatternAvailableProperty": 30040,
        "IsTogglePatternAvailableProperty": 30041,
        "IsTransformPattern2AvailableProperty": 30134,
        "IsTransformPatternAvailableProperty": 30042,
        "IsValuePatternAvailableProperty": 30043,
        "IsVirtualizedItemPatternAvailableProperty": 30109,
        "IsWindowPatternAvailableProperty": 30044,
        "ItemStatusProperty": 30026,
        "ItemTypeProperty": 30021,
        "LabeledByProperty": 30018,
        "LandmarkTypeProperty": 30157,
        "LegacyIAccessibleChildIdProperty": 30091,
        "LegacyIAccessibleDefaultActionProperty": 30100,
        "LegacyIAccessibleDescriptionProperty": 30094,
        "LegacyIAccessibleHelpProperty": 30097,
        "LegacyIAccessibleKeyboardShortcutProperty": 30098,
        "LegacyIAccessibleNameProperty": 30092,
        "LegacyIAccessibleRoleProperty": 30095,
        "LegacyIAccessibleSelectionProperty": 30099,
        "LegacyIAccessibleStateProperty": 30096,
        "LegacyIAccessibleValueProperty": 30093,
        "LevelProperty": 30154,
        "LiveSettingProperty": 30135,
        "LocalizedControlTypeProperty": 30004,
        "LocalizedLandmarkTypeProperty": 30158,
        "MultipleViewCurrentViewProperty": 30071,
        "MultipleViewSupportedViewsProperty": 30072,
        "NameProperty": 30005,
        "NativeWindowHandleProperty": 30020,
        "OptimizeForVisualContentProperty": 30111,
        "OrientationProperty": 30023,
        "OutlineColorProperty": 30161,
        "OutlineThicknessProperty": 30164,
        "PositionInSetProperty": 30152,
        "ProcessIdProperty": 30002,
        "ProviderDescriptionProperty": 30107,
        "RangeValueIsReadOnlyProperty": 30048,
        "RangeValueLargeChangeProperty": 30051,
        "RangeValueMaximumProperty": 30050,
        "RangeValueMinimumProperty": 30049,
        "RangeValueSmallChangeProperty": 30052,
        "RangeValueValueProperty": 30047,
        "RotationProperty": 30166,
        "RuntimeIdProperty": 30000,
        "ScrollHorizontalScrollPercentProperty": 30053,
        "ScrollHorizontalViewSizeProperty": 30054,
        "ScrollHorizontallyScrollableProperty": 30057,
        "ScrollVerticalScrollPercentProperty": 30055,
        "ScrollVerticalViewSizeProperty": 30056,
        "ScrollVerticallyScrollableProperty": 30058,
        "Selection2CurrentSelectedItemProperty": 30171,
        "Selection2FirstSelectedItemProperty": 30169,
        "Selection2ItemCountProperty": 30172,
        "Selection2LastSelectedItemProperty": 30170,
        "SelectionCanSelectMultipleProperty": 30060,
        "SelectionIsSelectionRequiredProperty": 30061,
        "SelectionItemIsSelectedProperty": 30079,
        "SelectionItemSelectionContainerProperty": 30080,
        "SelectionSelectionProperty": 30059,
        "SizeOfSetProperty": 30153,
        "SizeProperty": 30167,
        "SpreadsheetItemAnnotationObjectsProperty": 30130,
        "SpreadsheetItemAnnotationTypesProperty": 30131,
        "SpreadsheetItemFormulaProperty": 30129,
        "StylesExtendedPropertiesProperty": 30126,
        "StylesFillColorProperty": 30122,
        "StylesFillPatternColorProperty": 30125,
        "StylesFillPatternStyleProperty": 30123,
        "StylesShapeProperty": 30124,
        "StylesStyleIdProperty": 30120,
        "StylesStyleNameProperty": 30121,
        "TableColumnHeadersProperty": 30082,
        "TableItemColumnHeaderItemsProperty": 30085,
        "TableItemRowHeaderItemsProperty": 30084,
        "TableRowHeadersProperty": 30081,
        "TableRowOrColumnMajorProperty": 30083,
        "ToggleToggleStateProperty": 30086,
        "Transform2CanZoomProperty": 30133,
        "Transform2ZoomLevelProperty": 30145,
        "Transform2ZoomMaximumProperty": 30147,
        "Transform2ZoomMinimumProperty": 30146,
        "TransformCanMoveProperty": 30087,
        "TransformCanResizeProperty": 30088,
        "TransformCanRotateProperty": 30089,
        "ValueIsReadOnlyProperty": 30046,
        "ValueValueProperty" : 30045,
        "VisualEffectsProperty" : 30163,
        "WindowCanMaximizeProperty" :30073,
        "WindowCanMinimizeProperty" :30074,
        "WindowIsModalProperty" :30077,
        "WindowIsTopmostProperty" :30078,
        "WindowWindowInteractionStateProperty" :30076,
        "WindowWindowVisualStateProperty" :30075
}